### ISSUE TITLE
make this note a folder note on IOS

### ISSUE THREAD

**Issue by Fuguexv** [pjeby/note-folder-autorename#2]
Why can't I use the command "make this note a folder note" of this plugin on my iphone?

**Comment by pjeby** [comment]
Are there any error messages?  What happens if you manually create the folder first, does the command move the note into the folder?  That will help narrow down where the problem is.

**Comment by Fuguexv** [comment]
I opened Settings on the ios obsidian, open community plugins, found out Note folder autorename plugin, it was disabled and cant be enable~

**Comment by pjeby** [comment]
Ah.  Well, if you have a way to change the plugin's manifest.json to say `false` instead of `true` for `isDesktopOnly`, you should probably be able to enable it.  If it works, I can always release a new version with that change.

**Comment by Fuguexv** [comment]
It worked! Thank you!!!

**Comment by pjeby** [comment]
I've released an update which marks it as available on mobile now.
