### ISSUE TITLE
[bug report] Rename folder failed.

### ISSUE THREAD

**Issue by Andy-AO** [pjeby/note-folder-autorename#4]
The folder itself can be renamed, but links can't.

![image](https://user-images.githubusercontent.com/38101170/146848309-4dd8aadc-08da-496a-852a-a62d6246caf8.png)

https://user-images.githubusercontent.com/38101170/150449068-9bec170a-e260-4297-bf2c-74889210a5f3.mp4

You can download this zip file and use it to reproduce this problem.

[English(BUG ISSUE).zip](https://github.com/pjeby/note-folder-autorename/files/7909642/English.BUG.ISSUE.zip)

![image](https://user-images.githubusercontent.com/38101170/150449259-58c0fcd0-3b48-4183-b8be-ed8c4e8c6044.png)

# Reference
- [[bug report] Rename folder failed. · Issue #28 · pjeby/quick-explorer](https://github.com/pjeby/quick-explorer/issues/28)

**Comment by pjeby** [comment]
The zipfile you attached is empty except for an empty .obsidian directory -- not sure how to use this to reproduce anything?

**Comment by Andy-AO** [comment]
> The zipfile you attached is empty except for an empty .obsidian directory -- not sure how to use this to reproduce anything?

 Sorry, it's all my fault.  I have uploaded a new correct file.

[English(BUG Report).zip](https://github.com/pjeby/note-folder-autorename/files/7910924/English.BUG.Report.zip)

![image](https://user-images.githubusercontent.com/38101170/150478688-6d3fadb0-90a7-4a42-b85f-d0cf547e6486.png)

**Comment by pjeby** [comment]
Thanks for your patience!  It turns out the problem was with renaming folder notes with other folder notes inside of them.  I have uploaded the fix as version 0.1.2, please let me know if there is any further problem..

**Comment by Andy-AO** [comment]
> Thanks for your patience! It turns out the problem was with renaming folder notes with other folder notes inside of them. I have uploaded the fix as version 0.1.2, please let me know if there is any further problem..

It is working well now. what a ɡreat job! Thank you.
